src/app/views/market/market.component.ts, src/app/views/pool/pool.component.ts
Small changes to a couple of the indicator descriptions, so they're easier to take in.
=> Indicator descriptions

.github/workflows/main.yml
* Adds an action for discord notifications, when the repo is starred and a PR is created.
Needs the webhook adding to the repo.
=> Discord notifications

src/app/components/tables-module/tokens-table/tokens-table.component.html, src/app/components/tables-module/tokens-table/tokens-table.component.ts, src/app/components/tx-module/shared/percentage-amount-buttons/percentage-amount-buttons.component.ts, src/app/models/platform-api/requests/history-filter.ts, src/app/models/platform-api/responses/tokens/token-history-response.interface.ts, src/app/models/platform-api/responses/tokens/token.interface.ts, src/app/models/token-history.ts, src/app/services/api/platform-api.service.ts, src/app/services/platform/tokens.service.ts, src/app/services/utility/environments.service.ts, src/app/views/token/token.component.ts
PR for compatibility with https://github.com/Opdex/opdex-v1-api/pull/101 for updated token history filtering and pagination.
=> [PAPI-240] Token History Filter

src/app/components/tx-feed-module/tx-feed/tx-feed.component.ts, src/app/views/market/market.component.ts, src/app/views/pool/pool.component.html, src/app/views/pool/pool.component.ts, src/app/views/token/token.component.html, src/app/views/token/token.component.ts, src/app/views/wallet/wallet.component.html
[wapp-106] Finished updating transaction events string  with enum values
=> [wapp-106] Finished updating transaction events string  with enum values

src/app/components/cards-module/liquidity-pool-token-card/liquidity-pool-token-card.component.html, src/app/components/charts-module/line-chart/line-chart.component.html, src/app/components/tables-module/tokens-table/tokens-table.component.ts, src/app/models/market-history.ts, src/app/models/platform-api/requests/history-filter.ts, src/app/models/platform-api/responses/markets/market-history-response.interface.ts, src/app/models/platform-api/responses/markets/market-snapshot.interface.ts, src/app/services/api/platform-api.service.ts, src/app/services/api/rest-api.service.ts, src/app/services/platform/blocks.service.ts, src/app/services/platform/markets.service.ts, src/app/views/market/market.component.html, src/app/views/market/market.component.ts, src/app/views/pool/pool.component.ts, src/app/views/token/token.component.ts
- Update market history retrieval to use refactored endpoint
- Update history filter for more reusability
- Resolved bug with latest block Behavior Subject emitting Null
- Temporarily removed chart time frame selection capability
=> [PAPI-60] Market History

src/app/components/controls-module/token-keyword-filter-control/token-keyword-filter-control.component.ts, src/app/components/tx-module/tx-swap/tx-swap.component.ts, src/app/models/platform-api/requests/tokens/tokens-filter.ts, src/app/views/market/market.component.ts, src/app/views/tokens/tokens.component.ts
[wapp-107] Change string value to enum value for token filter
=> [wapp-107] Change string value to enum value for token filter

src/app/components/controls-module/token-keyword-filter-control/token-keyword-filter-control.component.ts, src/app/models/platform-api/requests/tokens/tokens-filter.ts, src/app/services/api/platform-api.service.ts, src/app/services/platform/wallets.service.ts, src/app/views/market/market.component.ts, src/app/views/tokens/tokens.component.ts, src/app/views/wallet/wallet.component.ts, src/environments/environment.ts
Change `provisional` query string to `tokenType` to match backend changes. 
Relates to: https://github.com/Opdex/opdex-v1-api/pull/109
=> [PAPI-231] Token Filter Change

src/app/lookups/pool-stat-cards.lookup.ts, src/app/views/pool/pool.component.ts
[wapp-109]: Moved pool stat card info to lookup
=> [wapp-109]: Moved pool stat card info to lookup

src/app/lookups/vault-stat-cards.lookup.ts, src/app/views/vault/vault.component.ts
[wapp-110]: Move vault stat card info to lookup
=> [wapp-110]: Move vault stat card info to lookup

src/app/lookups/governance-stat-cards.lookup.ts, src/app/views/governance/governance.component.html, src/app/views/governance/governance.component.ts
[wapp-111]: moved governance stat card info to class
=> [wapp-111]: moved governance stat card info to class

src/app/app.component.ts, src/app/views/auth/auth.component.ts
- Modify the endpoint connecting to sockets. 
- Initial SSAS setup getting SID on auth view
=> [PAPI-284] Socket Connection

src/app/components/controls-module/token-keyword-filter-control/token-keyword-filter-control.component.ts, src/app/components/navigation-module/side-nav/side-nav.component.html, src/app/components/tx-feed-module/tx-events/token-events/distribution-event/distribution-event.component.html, src/app/components/tx-feed-module/tx-summaries/create-pool-transaction-summary/create-pool-transaction-summary.component.html, src/app/components/tx-feed-module/tx-summaries/create-pool-transaction-summary/create-pool-transaction-summary.component.ts, src/app/components/tx-feed-module/tx-summaries/distribute-transaction-summary/distribute-transaction-summary.component.html, src/app/components/tx-module/shared/wallet-preview/wallet-preview.component.ts, src/app/components/tx-module/tx-create-pool/tx-create-pool.component.html, src/app/components/tx-module/tx-swap/tx-swap.component.ts, src/app/models/platform-api/requests/liquidity-pools/create-liquidity-pool-request.ts, src/app/services/platform/tokens.service.ts, src/app/views/mining-governance/mining-governance.component.html, src/app/views/mining-governance/mining-governance.component.ts, src/app/views/token/token.component.ts, src/app/views/vault/vault.component.ts, src/app/views/wallet/wallet.component.ts
- Resolves "Oops" error when quoting a create liquidity pool transaction.
- Resolves missing `marketAddress` value from quote request.
=> [WAPP-318] && [WAPP-128] Create LP Fixes

src/app/components/shared-module/qr-code/qr-code.component.html, src/app/components/shared-module/qr-code/qr-code.component.ts, src/app/components/tx-module/shared/review-quote/review-quote.component.html
Modifies the creation of transaction quote QR codes to be based on decoded Base64 quote requests. Make smaller QR codes and simplifies integrations with wallets and wallet helper tools.
=> [WAPP-131] Transaction QR Schema

package-lock.json, package.json, src/app/components/shared-module/qr-code/qr-code.component.html, src/app/lookups/environments.ts, src/app/models/platform-api/requests/auth/stratis-signature-auth-request.interface.ts, src/app/services/api/platform-api.service.ts, src/app/views/auth/auth.component.html, src/app/views/auth/auth.component.scss, src/app/views/auth/auth.component.ts
Implements the Stratis Signature Auth Spec into the authorization flows.
New auth flow using wallet or helper tools to sign, verify, and authenticate wallets using message signatures.
=> [WAPP-132] SSAS Implementation

src/app/components/controls-module/token-keyword-filter-control/token-keyword-filter-control.component.ts, src/app/models/platform-api/requests/tokens/tokens-filter.ts, src/app/models/platform-api/requests/wallets/wallet-balances-filter.ts, src/app/models/platform-api/responses/tokens/token.interface.ts, src/app/views/market/market.component.ts, src/app/views/tokens/tokens.component.ts, src/app/views/wallet/wallet.component.ts
=> [PAPI-325] Token Filtering by Attributes

src/app/components/controls-module/input-control/input-control.component.ts, src/app/components/controls-module/token-keyword-filter-control/token-keyword-filter-control.component.ts, src/app/components/navigation-module/side-nav/side-nav.component.html, src/app/components/tables-module/wallet-balances-table/wallet-balances-table.component.ts, src/app/components/tx-feed-module/tx-summaries/allowance-transaction-summary/allowance-transaction-summary.component.ts, src/app/components/tx-feed-module/tx-summaries/create-pool-transaction-summary/create-pool-transaction-summary.component.ts, src/app/components/tx-feed-module/tx-summaries/distribute-transaction-summary/distribute-transaction-summary.component.ts, src/app/components/tx-feed-module/tx-summaries/enable-mining-transaction-summary/enable-mining-transaction-summary.component.ts, src/app/components/tx-feed-module/tx-summaries/mine-transaction-summary/mine-transaction-summary.component.ts, src/app/components/tx-feed-module/tx-summaries/provide-transaction-summary/provide-transaction-summary.component.ts, src/app/components/tx-feed-module/tx-summaries/stake-transaction-summary/stake-transaction-summary.component.ts, src/app/components/tx-feed-module/tx-summaries/swap-transaction-summary/swap-transaction-summary.component.ts, src/app/components/tx-feed-module/tx-summaries/vault-proposal-transaction-summary/vault-proposal-transaction-summary.component.ts, src/app/components/tx-module/shared/pool-preview/pool-preview.component.ts, src/app/components/tx-module/tx-mine/tx-mine-start/tx-mine-start.component.ts, src/app/components/tx-module/tx-mine/tx-mine-stop/tx-mine-stop.component.ts, src/app/components/tx-module/tx-provide/tx-provide-add/tx-provide-add.component.ts, src/app/components/tx-module/tx-provide/tx-provide-remove/tx-provide-remove.component.ts, src/app/components/tx-module/tx-stake/tx-stake-start/tx-stake-start.component.ts, src/app/components/tx-module/tx-stake/tx-stake-stop/tx-stake-stop.component.ts, src/app/components/tx-module/tx-vault-proposal/tx-vault-proposal-create/tx-vault-proposal-create.component.html, src/app/components/tx-module/tx-vault-proposal/tx-vault-proposal-create/tx-vault-proposal-create.component.ts, src/app/services/platform/liquidity-pools.service.ts, src/app/services/platform/tokens.service.ts, src/app/services/platform/transactions.service.ts, src/app/services/utility/cache.service.ts, src/app/views/pool/pool.component.ts
- Changing liquidity pools, resets any forms in the transaction sidebar
- Resolves caching bug when using `cacheOnly` flag
- 500 CRS proposal deposit balance validation
=> Pool Select Reset Tx Sidebar

src/app/components/cards-module/liquidity-pool-card/liquidity-pool-card.component.html, src/app/components/cards-module/mining-card/mining-card.component.html, src/app/components/cards-module/mining-card/mining-card.component.ts, src/app/components/cards-module/staking-pool-card/staking-pool-card.component.html, src/app/components/tables-module/wallet-mining-positions-table/wallet-mining-positions-table.component.ts, src/app/components/tx-feed-module/tx-summaries/enable-mining-transaction-summary/enable-mining-transaction-summary.component.ts, src/app/components/tx-module/shared/pool-preview/pool-preview.component.ts, src/app/components/tx-module/tx-base.component.ts, src/app/components/tx-module/tx-mine/tx-mine-collect/tx-mine-collect.component.ts, src/app/components/tx-module/tx-mine/tx-mine-start/tx-mine-start.component.ts, src/app/components/tx-module/tx-mine/tx-mine-stop/tx-mine-stop.component.html, src/app/components/tx-module/tx-mine/tx-mine-stop/tx-mine-stop.component.ts, src/app/components/tx-module/tx-mine/tx-mine.component.html, src/app/lookups/pool-stat-cards.lookup.ts, src/app/models/platform-api/responses/liquidity-pools/liquidity-pool-responses.interface.ts, src/app/views/market/market.component.ts, src/app/views/mining-governance/mining-governance.component.ts, src/app/views/pool/pool.component.html, src/app/views/pool/pool.component.ts, src/app/views/pools/pools.component.ts, src/app/views/tokens/tokens.component.ts
Moves mining pool from liquidity pool summary to top level.
=> Liquidity Pool Response Model

src/app/components/tx-module/shared/allowance-validation/allowance-validation.component.html, src/app/components/tx-module/shared/pool-preview/pool-preview.component.html, src/app/components/tx-module/shared/pool-preview/pool-preview.component.ts, src/app/components/tx-module/tx-allowance/tx-allowance.component.html, src/app/components/tx-module/tx-mine/tx-mine-start/tx-mine-start.component.html, src/app/components/tx-module/tx-mine/tx-mine-start/tx-mine-start.component.ts, src/app/components/tx-module/tx-mine/tx-mine-stop/tx-mine-stop.component.html, src/app/components/tx-module/tx-mine/tx-mine-stop/tx-mine-stop.component.ts, src/app/components/tx-module/tx-provide/tx-provide-add/tx-provide-add.component.html, src/app/components/tx-module/tx-provide/tx-provide-add/tx-provide-add.component.ts, src/app/components/tx-module/tx-provide/tx-provide-remove/tx-provide-remove.component.html, src/app/components/tx-module/tx-provide/tx-provide-remove/tx-provide-remove.component.ts, src/app/components/tx-module/tx-sidebar/tx-sidebar.component.ts, src/app/components/tx-module/tx-stake/tx-stake-start/tx-stake-start.component.html, src/app/components/tx-module/tx-stake/tx-stake-start/tx-stake-start.component.ts, src/app/components/tx-module/tx-stake/tx-stake-stop/tx-stake-stop.component.html, src/app/components/tx-module/tx-stake/tx-stake-stop/tx-stake-stop.component.ts, src/app/components/tx-module/tx-swap/tx-swap.component.html, src/app/components/tx-module/tx-vault-proposal/tx-vault-proposal-create/tx-vault-proposal-create.component.html, src/app/components/tx-module/tx-vault-proposal/tx-vault-proposal-create/tx-vault-proposal-create.component.scss, src/app/lookups/transaction-types.lookup.ts, src/app/models/transaction-receipt.ts
Shows estimations and percentages of provide, mine and stake transaction types.
=> Transaction Quote Improvements

src/app/app-routing.module.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/components/navigation-module/mobile-nav/mobile-nav.component.html, src/app/components/navigation-module/mobile-nav/mobile-nav.component.ts, src/app/components/navigation-module/side-nav/side-nav.component.html, src/app/components/navigation-module/side-nav/side-nav.component.ts, src/app/components/shared-module/shared.module.ts, src/app/components/shared-module/tx-quote-submit-button/tx-quote-submit-button.component.html, src/app/components/shared-module/tx-quote-submit-button/tx-quote-submit-button.component.ts, src/app/lookups/environments.ts, src/app/services/api/auth-api.service.ts, src/app/services/api/platform-api.service.ts, src/app/services/guards/auth.guard.ts, src/app/services/utility/environments.service.ts, src/app/services/utility/jwt.service.ts, src/app/views/auth/auth.component.html, src/app/views/auth/auth.component.ts, src/app/views/login/login.component.spec.ts, src/app/views/login/login.component.ts, src/environments/environment.mainnet.ts, src/environments/environment.prod.ts, src/environments/environment.testnet.ts, src/environments/environment.ts
- Accepts and access_code from auth server redirects
- Makes request to Auth Server to exchange access_code for jwt access_token
- Adds login view that immediately redirects users to auth server UI
=> [WAPP-172] Auth Access Code Flow

src/app/components/charts-module/candle-chart/candle-chart.component.ts, src/app/components/charts-module/line-chart/line-chart.component.ts, src/app/components/charts-module/volume-chart/volume-chart.component.ts, src/app/views/pool/pool.component.html
Attempts to resolve a bug where line charts display duplicate datasets overlaying each other at times.
=> [WAPP-171] Line Chart Bug

src/app/components/shared-module/number/number.component.html, src/app/components/tables-module/pools-table/pools-table.component.html, src/app/components/tables-module/vault-proposal-pledges-table/vault-proposal-pledges-table.component.html, src/app/components/tables-module/vault-proposal-votes-table/vault-proposal-votes-table.component.html, src/app/components/tables-module/wallet-balances-table/wallet-balances-table.component.html, src/app/components/tables-module/wallet-balances-table/wallet-balances-table.component.ts, src/app/components/tables-module/wallet-mining-positions-table/wallet-mining-positions-table.component.html, src/app/components/tables-module/wallet-mining-positions-table/wallet-mining-positions-table.component.ts, src/app/components/tables-module/wallet-provisioning-positions-table/wallet-provisioning-positions-table.component.html, src/app/components/tables-module/wallet-provisioning-positions-table/wallet-provisioning-positions-table.component.ts, src/app/components/tables-module/wallet-staking-positions-table/wallet-staking-positions-table.component.html, src/app/components/tables-module/wallet-staking-positions-table/wallet-staking-positions-table.component.ts, src/app/components/tx-module/shared/wallet-preview/wallet-preview.component.ts, src/app/enums/icons.ts, src/app/models/address-position.ts, src/app/models/ui/tokens/token.ts, src/app/services/api/platform-api.service.ts, src/app/services/platform/wallets.service.ts, src/app/views/pool/pool.component.ts, src/app/views/token/token.component.ts, src/app/views/wallet/wallet.component.html, src/app/views/wallet/wallet.component.scss, src/app/views/wallet/wallet.component.ts, src/scss/animations.scss, src/scss/app.scss, src/scss/theming/layout.scss
Adds a refresh buttons to positions in the wallet view.
=> Position Refresh Trigger

src/app/components/navigation-module/mobile-nav/mobile-nav.component.html, src/app/components/navigation-module/mobile-nav/mobile-nav.component.ts, src/app/components/navigation-module/side-nav/side-nav.component.html, src/app/components/navigation-module/side-nav/side-nav.component.ts, src/app/services/api/rest-api.service.ts, src/app/services/utility/environments.service.ts, src/app/views/auth/auth.component.html, src/app/views/auth/auth.component.ts
- Removes old code for the legacy wallet auth flows
- Replaced with new OAuth server flows
=> Remove Legacy Auth Flows

src/app/views/pool/pool.component.html, src/app/views/pool/pool.component.ts, src/app/views/token/token.component.html, src/app/views/token/token.component.ts
- Cleans legacy code no longer used 
- Improves template logic
=> [WAPP-183] Refactor Token and Pool Components

src/app/components/cards-module/vault-proposal-card/vault-proposal-card.component.html, src/app/components/cards-module/vault-proposal-card/vault-proposal-card.component.ts, src/app/components/controls-module/input-control/input-control.component.html, src/app/components/tx-module/shared/percentage-amount-buttons/percentage-amount-buttons.component.html, src/app/components/tx-module/shared/percentage-amount-buttons/percentage-amount-buttons.component.ts, src/app/components/tx-module/shared/vault-proposal-selector/vault-proposal-selector.component.html, src/app/components/tx-module/shared/vault-proposal-selector/vault-proposal-selector.component.spec.ts, src/app/components/tx-module/shared/vault-proposal-selector/vault-proposal-selector.component.ts, src/app/components/tx-module/tx-base.component.ts, src/app/components/tx-module/tx-vault-proposal/tx-vault-proposal-create/tx-vault-proposal-create.component.html, src/app/components/tx-module/tx-vault-proposal/tx-vault-proposal-pledge/tx-vault-proposal-pledge.component.html, src/app/components/tx-module/tx-vault-proposal/tx-vault-proposal-pledge/tx-vault-proposal-pledge.component.ts, src/app/components/tx-module/tx-vault-proposal/tx-vault-proposal-vote/tx-vault-proposal-vote.component.html, src/app/components/tx-module/tx-vault-proposal/tx-vault-proposal-vote/tx-vault-proposal-vote.component.ts, src/app/components/tx-module/tx-vault-proposal/tx-vault-proposal.component.html, src/app/components/tx-module/tx-vault-proposal/tx-vault-proposal.component.ts, src/app/components/tx-module/tx.module.ts, src/app/services/platform/wallets.service.ts, src/app/services/utility/cache.service.ts
- Proposal selector similar to LP selector
- Improved create/pledge/vote form UI and validations
=> [WAPP-139] Proposal Improvements

azure-pipelines.yml
Devnet is no longer used, remove it from release pipelines
=> Remove Devnet From Pipelines
